#!/usr/bin/env python3
import sys
from decimal import Decimal, ROUND_HALF_UP


def solve(X: Decimal):
    print(X.quantize(Decimal(0), ROUND_HALF_UP))


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = Decimal(next(tokens))  # type: float
    solve(X)


if __name__ == '__main__':
    main()
